version: '3'
services:
        web:
                image: flask_swifties_v1
                build: .
                ports:
                        - "8036:8036"
                volumes:
                        - ./volumes:/volumes
                        - ./instance:/instance
                restart: unless-stopped
